### ISSUE TITLE
[StreamsCharts] HTTP 403 errors getting VOD

### ISSUE THREAD

**Issue by Infinitay** [vyneer/tbf#1]
Seems like lately TBF has been getting triggered by what I assume is Cloudflare? I keep getting the following error
> [2022-09-04T21:45:08.673Z ERROR tbf] couldn't process the url: HTTP status client error (403 Forbidden) for url (https://streamscharts.com/channels/robcdee/streams/39638619239)

Though on the other hand, it usually works after 3-6 attempts

**Comment by vyneer** [comment]
I think i fixed it in e0df5ea279c038efc9cf221965a02e9d243fa769

Thanks for letting me know <3

**Comment by Infinitay** [comment]
Happening again except this time it seems like it 403s despite the number of attempts and user-agent.

**Comment by vyneer** [comment]
Can't seem to reproduce, works fine for me both on Linux and Windows, the user-agent test passes as well. Maybe your IP/your PC is getting flagged by Cloudflare's bot detection thing? Don't know how much I can do about that.

**Comment by Infinitay** [comment]
Oddly enough it started working again. Not sure what that was all about I guess because I haven't done anything really.
